# Generated by Django 5.0.7 on 2024-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100, verbose_name='Task Title')),
                ('taskDescription', models.TextField(verbose_name='Task Description')),
                ('iscompleted', models.BooleanField(default=False, verbose_name='Is Completed?')),
                ('taskAssignDate', models.DateField(auto_now_add=True, verbose_name='Task Date')),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
